language:
  - node_js
node_js:
  - 9.7.1
before_install:
  - gem update --system
  - gem install sass --version "=3.4.20"
  - gem install compass --version "=1.0.3"
install:
  - npm install
os:
  - linux
addons:
  ssh_known_hosts:
  - 0.0.0.0
deploy:
  # deploy stage to the unstabled stage environment
  - provider: script
    skip_cleanup: true
    script: rsync -r $TRAVIS_BUILD_DIR/dist/ travis@0.0.0.0:/path/to/dist
    on:
      branch: stage
  # deploy deploy to production
  - provider: script
    skip_cleanup: true
    script:
      - rsync -r $TRAVIS_BUILD_DIR/dist/ travis@0.0.0.0:/path/to/dist
    on:
      branch: deploy
before_deploy:
  - openssl aes-256-cbc -K $encrypted_nnnnnnnn_key -iv $encrypted_nnnnnnnn_iv -in travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/travis_rsa
  - ssh-add ~/.ssh/travis_rsa
script:
  - if [ "$TRAVIS_BRANCH" = "stage" ]; then grunt build --environment="staging"; fi
  - if [ "$TRAVIS_BRANCH" = "deploy" ]; then grunt build --environment="production"; fi
