language:
  - python
  - node_js
node_js:
  - 9.7.1
python:
  - 3.6
cache:
  directories:
    - node_modules
install:
  - if [ "$TRAVIS_BRANCH" = "stage" ]; then pip install -r ./requirements/development.txt; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install -r ./requirements/production.txt; fi
  - npm install
os:
  - linux
script:
  - nosetests -v
  - pycodestyle ./app.py
  - pep257 ./app.py
before_deploy:
  - npm install -g serverless serverless-domain-manager serverless-python-requirements serverless-wsgi
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - sls deploy
    on:
        branch: master 
